<?php

declare(strict_types=1);

namespace JohnWink\En16931\Tools;

use JohnWink\En16931\RuleSets;
use RuntimeException;

/**
 * Renders the rule-coverage documentation (COVERAGE.md + the README summary)
 * by diffing the rules registered in {@see RuleSets} against the official
 * reference list in resources/rules-reference.json (built by
 * tools/build-rules-reference.php from the EN 16931 / KoSIT Schematron).
 *
 * Guarded by tests/Feature/CoverageDocTest.php so the docs cannot drift.
 */
final class CoverageMatrix
{
    public const string README_START = '<!-- coverage:start — generated by tools/generate-coverage.php, do not edit -->';

    public const string README_END = '<!-- coverage:end -->';

    /**
     * TaxableSumRule registers as "BR-CAT-08" but reports one of these ids.
     */
    private const array CATEGORY_SUM_IDS = ['BR-S-08', 'BR-Z-08', 'BR-E-08', 'BR-AE-08', 'BR-IC-08', 'BR-G-08', 'BR-O-08', 'BR-IG-08', 'BR-IP-08'];

    /**
     * Rules whose implementation deviates from the official scope (🟡).
     *
     * @var array<string, string>
     */
    private const array PARTIAL = [];

    /**
     * Rules whose official assert is `true()` — not machine-checkable, so
     * there is nothing to implement (✅ + note).
     *
     * @var array<string, string>
     */
    private const array NOT_ENFORCEABLE = [
        'BR-CO-05' => 'Official assert is `true()` — not machine-checkable; trivially satisfied.',
        'BR-CO-06' => 'Official assert is `true()` — not machine-checkable; trivially satisfied.',
        'BR-CO-07' => 'Official assert is `true()` — not machine-checkable; trivially satisfied.',
        'BR-CO-08' => 'Official assert is `true()` — not machine-checkable; trivially satisfied.',
        'BR-CO-27' => 'Official assert (IBAN or proprietary id or neither) is a tautology; it never rejects.',
    ];

    /**
     * Implemented rules with a noteworthy (deliberate) deviation (✅ + note).
     *
     * @var array<string, string>
     */
    private const array NOTES = [
        'BR-CO-16' => 'Severity: warning — the KoSIT/XRechnung configuration treats BR-CO-16 as informational; the pure EN 16931 artefacts flag it fatal.',
        'BR-CL-10' => 'Severity: warning (KoSIT scenario downgrade); the official list additionally allows the SEPA identifier.',
        'BR-CL-11' => 'Severity: warning — the KoSIT/XRechnung scenarios downgrade this code-list check.',
        'BR-CL-21' => 'Severity: warning — the KoSIT/XRechnung scenarios downgrade this code-list check.',
        'BR-CL-23' => 'Severity: warning — the KoSIT/XRechnung scenarios downgrade this code-list check.',
        'BR-CL-24' => 'Severity: warning — the KoSIT/XRechnung scenarios downgrade this code-list check.',
        'BR-CL-25' => 'Severity: warning — the KoSIT/XRechnung scenarios downgrade this code-list check.',
        'BR-CL-26' => 'Severity: warning — the KoSIT/XRechnung scenarios downgrade this code-list check.',
        'BR-CO-17' => 'Stricter than official: exact equality required, the official artefacts allow a ±0.01 rounding tolerance.',
        'BR-S-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-Z-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-E-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-AE-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-IC-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-G-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-O-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-IG-08' => 'Grouped per (category, rate) for every category — equivalent in practice since the other categories carry rate 0.',
        'BR-IP-08' => 'Grouped per (category, rate) for every category — equivalent in practice since the other categories carry rate 0.',
        'BR-Z-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-E-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-AE-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-IC-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-G-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-O-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
    ];

    /**
     * Rules counted as open although an id-equal rule is registered (❌ + note).
     * Use this when a registered rule id does not carry the official semantics.
     *
     * @var array<string, string>
     */
    private const array FORCED_OPEN = [];

    /**
     * Implemented rules that are absent from the reference version (extra section).
     *
     * @var array<string, string>
     */
    private const array EXTRA_NOTES = [
        'BR-DE-CVD-01' => 'Clean Vehicles Directive profile — a separate KoSIT scenario, not part of the standard XRechnung configuration. Enforced only for CVD-profile invoices.',
        'BR-DE-CVD-02' => 'Clean Vehicles Directive profile — enforced only for CVD-profile invoices (separate KoSIT scenario).',
        'BR-DE-CVD-03' => 'Clean Vehicles Directive profile — enforced only for CVD-profile invoices (separate KoSIT scenario).',
        'BR-DE-CVD-04' => 'Clean Vehicles Directive profile — enforced only for CVD-profile invoices (separate KoSIT scenario).',
        'BR-DE-CVD-05' => 'Clean Vehicles Directive profile — enforced only for CVD-profile invoices (separate KoSIT scenario).',
        'BR-DE-CVD-06-a' => 'Clean Vehicles Directive profile — enforced only for CVD-profile invoices (separate KoSIT scenario).',
        'BR-DE-CVD-06-b' => 'Clean Vehicles Directive profile — enforced only for CVD-profile invoices (separate KoSIT scenario).',
        'BR-TMP-CVD-01' => 'Clean Vehicles Directive profile — enforced only for CVD-profile invoices (separate KoSIT scenario).',
    ];

    public static function renderCoverage(): string
    {
        $reference = self::reference();
        $implemented = self::implementedRuleIds();
        $groups = self::groupedReference($reference['rules']);

        $markdown = "# Rule coverage\n\n";
        $markdown .= "> Generated by `php tools/generate-coverage.php` — do not edit by hand.\n";
        $markdown .= '> Reference: '.$reference['source'].' — the compiled Schematron the official KoSIT validator runs, i.e. the legal conformance target and the parity oracle.'."\n\n";
        $markdown .= "**Legend:** ✅ implemented · 🟡 partial / deviating (see note) · ❌ not implemented yet\n\n";
        $markdown .= self::pipelineOverview($groups, $implemented);
        $markdown .= self::renderSummaryTable($groups, $implemented, '## Business rules');
        $markdown .= "\nThe per-rule matrix below covers stage 3 (the EN 16931 business rules). Stages 1 and 2 are covered wholesale — the XSD schemas and every syntax rule — and summarised above.\n";

        foreach ($groups as $label => $rules) {
            $markdown .= "\n## {$label}\n\n";
            $markdown .= "| Rule | Status | Flag | Official text | Note |\n|---|:-:|---|---|---|\n";

            foreach ($rules as $rule) {
                [$status, $note] = self::statusFor($rule['id'], $implemented);
                $markdown .= '| '.$rule['id'].' | '.$status.' | '.$rule['flag'].' | '.self::cell($rule['text']).' | '.self::cell($note)." |\n";
            }
        }

        $extras = array_diff($implemented, array_column($reference['rules'], 'id'));

        if ($extras !== []) {
            $markdown .= "\n## Implemented beyond the reference\n\n| Rule | Note |\n|---|---|\n";

            foreach ($extras as $extra) {
                $markdown .= '| '.$extra.' | '.self::cell(self::EXTRA_NOTES[$extra] ?? '')." |\n";
            }
        }

        return $markdown;
    }

    /**
     * The full README block, markers included, so the drift test can match exactly.
     */
    public static function readmeBlock(): string
    {
        $reference = self::reference();
        $implemented = self::implementedRuleIds();
        $groups = self::groupedReference($reference['rules']);

        [$done, $partial, $open, $total] = self::totals($groups, $implemented);

        $block = self::README_START."\n\n";
        $block .= self::pipelineOverview($groups, $implemented);
        $block .= "### Business rules\n\n";
        $block .= "**{$done} of {$total} rules implemented ({$partial} partial, {$open} open)** — measured against the ";
        $block .= $reference['source'].', the compiled Schematron the official KoSIT validator runs (and the parity oracle). ';
        $block .= "The full per-rule matrix lives in [COVERAGE.md](COVERAGE.md).\n\n";
        $block .= self::renderSummaryTable($groups, $implemented, null);
        $block .= "\n".self::README_END;

        return $block;
    }

    /**
     * The three-stage pipeline overview: XSD schema, syntax rules (UBL-CR/SR,
     * CII-SR/DT) and the EN 16931 / XRechnung business rules. Stages 1 and 2 are
     * covered wholesale (bundled schemas + every syntax rule) so only their totals
     * are shown; stage 3 has the full per-rule matrix below.
     *
     * @param  array<string, list<array{id: string, set: string, flag: string, text: string}>>  $groups
     * @param  list<string>  $implemented
     */
    private static function pipelineOverview(array $groups, array $implemented): string
    {
        [$brDone, , , $brTotal] = self::totals($groups, $implemented);
        $counts = self::syntaxCounts();
        $syntax = array_sum($counts);

        $markdown = "## Validation pipeline\n\n";
        $markdown .= "Validation runs the three stages the official KoSIT validator applies — natively in PHP, no Java:\n\n";
        $markdown .= "| Stage | Checks | Rules | Status |\n|---|---|--:|:-:|\n";
        $markdown .= "| 1 — XSD schema | Structure of UBL 2.1 Invoice/CreditNote & CII D16B | — | ✅ bundled |\n";
        $markdown .= "| 2 — Syntax rules | UBL-CR/SR & CII-SR/DT code-list, cardinality & datatype restrictions | {$syntax} | ✅ {$syntax} / {$syntax} |\n";
        $markdown .= "| 3 — Business rules | EN 16931 core + XRechnung CIUS/Extension | {$brTotal} | ✅ {$brDone} / {$brTotal} |\n\n";
        $markdown .= sprintf(
            "Stage 2 breakdown: **UBL-CR %d, UBL-SR %d, CII-SR %d, CII-DT %d**. Evaluated directly against the DOM by `SchematronEngine` from `resources/syntax-rules.json` — proven against the KoSIT validator over the full official instance suite (0 false positives).\n\n",
            $counts['UBL-CR-'],
            $counts['UBL-SR-'],
            $counts['CII-SR-'],
            $counts['CII-DT-'],
        );

        return $markdown;
    }

    /**
     * Syntax-rule totals per prefix, read from resources/syntax-rules.json
     * (built by tools/build-syntax-rules.php from the KoSIT configuration).
     *
     * @return array{'UBL-CR-': int, 'UBL-SR-': int, 'CII-SR-': int, 'CII-DT-': int}
     */
    private static function syntaxCounts(): array
    {
        $path = dirname(__DIR__).'/resources/syntax-rules.json';
        $json = file_get_contents($path);

        if ($json === false) {
            throw new RuntimeException("Missing {$path} — run: php tools/build-syntax-rules.php");
        }

        /** @var array{rules: list<array{id: string}>} $data */
        $data = json_decode($json, true, 512, JSON_THROW_ON_ERROR);

        $counts = ['UBL-CR-' => 0, 'UBL-SR-' => 0, 'CII-SR-' => 0, 'CII-DT-' => 0];

        foreach ($data['rules'] as $rule) {
            foreach ($counts as $prefix => $count) {
                if (str_starts_with($rule['id'], $prefix)) {
                    $counts[$prefix] = $count + 1;

                    break;
                }
            }
        }

        return $counts;
    }

    /**
     * @param  array<string, list<array{id: string, set: string, flag: string, text: string}>>  $groups
     */
    private static function renderSummaryTable(array $groups, array $implemented, ?string $heading): string
    {
        $markdown = $heading !== null ? "{$heading}\n\n" : '';
        $markdown .= "| Rule group | ✅ | 🟡 | ❌ | Total |\n|---|--:|--:|--:|--:|\n";

        foreach ($groups as $label => $rules) {
            [$done, $partial, $open] = self::countStatuses($rules, $implemented);
            $markdown .= "| {$label} | {$done} | {$partial} | {$open} | ".count($rules)." |\n";
        }

        [$done, $partial, $open, $total] = self::totals($groups, $implemented);
        $markdown .= "| **Total** | **{$done}** | **{$partial}** | **{$open}** | **{$total}** |\n";

        return $markdown;
    }

    /**
     * @param  array<string, list<array{id: string, set: string, flag: string, text: string}>>  $groups
     * @return array{int, int, int, int}
     */
    private static function totals(array $groups, array $implemented): array
    {
        $done = $partial = $open = $total = 0;

        foreach ($groups as $rules) {
            [$groupDone, $groupPartial, $groupOpen] = self::countStatuses($rules, $implemented);
            $done += $groupDone;
            $partial += $groupPartial;
            $open += $groupOpen;
            $total += count($rules);
        }

        return [$done, $partial, $open, $total];
    }

    /**
     * @param  list<array{id: string, set: string, flag: string, text: string}>  $rules
     * @param  list<string>  $implemented
     * @return array{int, int, int}
     */
    private static function countStatuses(array $rules, array $implemented): array
    {
        $done = $partial = $open = 0;

        foreach ($rules as $rule) {
            [$status] = self::statusFor($rule['id'], $implemented);
            match ($status) {
                '✅' => $done++,
                '🟡' => $partial++,
                default => $open++,
            };
        }

        return [$done, $partial, $open];
    }

    /**
     * @param  list<string>  $implemented
     * @return array{string, string}
     */
    private static function statusFor(string $id, array $implemented): array
    {
        if (isset(self::FORCED_OPEN[$id])) {
            return ['❌', self::FORCED_OPEN[$id]];
        }

        if (isset(self::NOT_ENFORCEABLE[$id])) {
            return ['✅', self::NOT_ENFORCEABLE[$id]];
        }

        if (isset(self::PARTIAL[$id])) {
            return ['🟡', self::PARTIAL[$id]];
        }

        if (in_array($id, $implemented, true)) {
            return ['✅', self::NOTES[$id] ?? ''];
        }

        return ['❌', ''];
    }

    /**
     * @param  list<array{id: string, set: string, flag: string, text: string}>  $rules
     * @return array<string, list<array{id: string, set: string, flag: string, text: string}>>
     */
    private static function groupedReference(array $rules): array
    {
        $labels = [
            'BR-CO-' => 'BR-CO — conditions & calculations',
            'BR-DEC-' => 'BR-DEC — decimals',
            'BR-CL-' => 'BR-CL — code lists',
            'BR-AE-' => 'BR-AE — Reverse charge',
            'BR-IG-' => 'BR-IG — IGIC (Canary Islands)',
            'BR-IP-' => 'BR-IP — IPSI (Ceuta/Melilla)',
            'BR-IC-' => 'BR-IC — Intra-community supply',
            'BR-S-' => 'BR-S — Standard rated',
            'BR-Z-' => 'BR-Z — Zero rated',
            'BR-E-' => 'BR-E — Exempt from VAT',
            'BR-G-' => 'BR-G — Export outside the EU',
            'BR-O-' => 'BR-O — Not subject to VAT',
            'BR-B-' => 'BR-B — Split payment (Italy)',
        ];

        $order = [
            'BR — core document & line rules',
            ...array_values($labels),
            'BR-DE — XRechnung CIUS',
            'BR-DEX — XRechnung Extension',
        ];

        $groups = array_fill_keys($order, []);

        foreach ($rules as $rule) {
            if ($rule['set'] === 'xrechnung') {
                $groups[str_starts_with($rule['id'], 'BR-DEX') ? 'BR-DEX — XRechnung Extension' : 'BR-DE — XRechnung CIUS'][] = $rule;

                continue;
            }

            $label = 'BR — core document & line rules';

            foreach ($labels as $prefix => $candidate) {
                if (str_starts_with($rule['id'], $prefix)) {
                    $label = $candidate;

                    break;
                }
            }

            $groups[$label][] = $rule;
        }

        return array_filter($groups, static fn (array $groupRules): bool => $groupRules !== []);
    }

    /**
     * @return array{source: string, rules: list<array{id: string, set: string, flag: string, text: string}>}
     */
    private static function reference(): array
    {
        $path = dirname(__DIR__).'/resources/rules-reference.json';
        $json = file_get_contents($path);

        if ($json === false) {
            throw new RuntimeException("Missing {$path} — run: php tools/build-rules-reference.php");
        }

        /** @var array{source: string, rules: list<array{id: string, set: string, flag: string, text: string}>} */
        return json_decode($json, true, 512, JSON_THROW_ON_ERROR);
    }

    /**
     * @return list<string>
     */
    private static function implementedRuleIds(): array
    {
        $ids = [];

        foreach ([...RuleSets::en16931(), ...RuleSets::xrechnung()] as $rule) {
            if ($rule->id() === 'BR-CAT-08') {
                array_push($ids, ...self::CATEGORY_SUM_IDS);

                continue;
            }

            $ids[] = $rule->id();
        }

        $ids = array_values(array_unique($ids));
        sort($ids, SORT_NATURAL);

        return $ids;
    }

    private static function cell(string $text): string
    {
        return str_replace('|', '\\|', $text);
    }
}
