<?php

declare(strict_types=1);

namespace JohnWink\En16931\Tools;

use JohnWink\En16931\RuleSets;
use RuntimeException;

/**
 * Renders the rule-coverage documentation (COVERAGE.md + the README summary)
 * by diffing the rules registered in {@see RuleSets} against the official
 * reference list in resources/rules-reference.json (built by
 * tools/build-rules-reference.php from the EN 16931 / KoSIT Schematron).
 *
 * Guarded by tests/Feature/CoverageDocTest.php so the docs cannot drift.
 */
final class CoverageMatrix
{
    public const string README_START = '<!-- coverage:start — generated by tools/generate-coverage.php, do not edit -->';

    public const string README_END = '<!-- coverage:end -->';

    /**
     * TaxableSumRule registers as "BR-CAT-08" but reports one of these ids.
     */
    private const array CATEGORY_SUM_IDS = ['BR-S-08', 'BR-Z-08', 'BR-E-08', 'BR-AE-08', 'BR-IC-08', 'BR-G-08', 'BR-O-08'];

    /**
     * Rules whose implementation deviates from the official scope (🟡).
     *
     * @var array<string, string>
     */
    private const array PARTIAL = [
        'BR-AE-02' => 'Simplified: requires the Seller VAT identifier (BT-31) only; officially BT-31, BT-32 or the tax representative VAT identifier (BT-63) qualify — BT-32/BT-63 are not modelled yet.',
        'BR-AE-03' => 'Simplified: checks the Buyer VAT identifier for any AE usage; officially -03 is the document-allowance trigger (the buyer check for AE lines belongs to BR-AE-02).',
        'BR-CL-14' => 'Checked for the seller (BT-40) and buyer (BT-55) country only; BT-69 (tax representative) and BT-80 (deliver-to) are not modelled yet.',
    ];

    /**
     * Implemented rules with a noteworthy (deliberate) deviation (✅ + note).
     *
     * @var array<string, string>
     */
    private const array NOTES = [
        'BR-CO-16' => 'Severity: warning — the KoSIT/XRechnung configuration treats BR-CO-16 as informational; the pure EN 16931 artefacts flag it fatal.',
        'BR-CO-17' => 'Stricter than official: exact equality required, the official artefacts allow a ±0.01 rounding tolerance.',
        'BR-S-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-Z-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-E-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-AE-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-IC-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-G-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-O-08' => 'Grouped per (category, rate) for every category; officially only S splits per rate — equivalent in practice since the other categories carry rate 0.',
        'BR-Z-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-E-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-AE-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-IC-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-G-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
        'BR-O-09' => 'A missing BT-117 passes (presence is owned by BR-46).',
    ];

    /**
     * Rules counted as open although an id-equal rule is registered (❌ + note).
     * Use this when a registered rule id does not carry the official semantics.
     *
     * @var array<string, string>
     */
    private const array FORCED_OPEN = [];

    /**
     * Implemented rules that are absent from the reference version (extra section).
     *
     * @var array<string, string>
     */
    private const array EXTRA_NOTES = [
        'BR-CO-25' => 'Removed from the EN 16931 artefacts in 1.3.16, but still active in the KoSIT XRechnung 3.0.2 scenario this library is proven against.',
    ];

    public static function renderCoverage(): string
    {
        $reference = self::reference();
        $implemented = self::implementedRuleIds();
        $groups = self::groupedReference($reference['rules']);

        $markdown = "# Rule coverage\n\n";
        $markdown .= "> Generated by `php tools/generate-coverage.php` — do not edit by hand.\n";
        $markdown .= '> Reference: EN 16931 validation artefacts **'.$reference['sources']['en16931']['version'].'** (UBL) · XRechnung Schematron **'.$reference['sources']['xrechnung']['version']."**.\n\n";
        $markdown .= "**Legend:** ✅ implemented · 🟡 partial / deviating (see note) · ❌ not implemented yet\n\n";
        $markdown .= self::renderSummaryTable($groups, $implemented, '## Summary');

        foreach ($groups as $label => $rules) {
            $markdown .= "\n## {$label}\n\n";
            $markdown .= "| Rule | Status | Flag | Official text | Note |\n|---|:-:|---|---|---|\n";

            foreach ($rules as $rule) {
                [$status, $note] = self::statusFor($rule['id'], $implemented);
                $markdown .= '| '.$rule['id'].' | '.$status.' | '.$rule['flag'].' | '.self::cell($rule['text']).' | '.self::cell($note)." |\n";
            }
        }

        $extras = array_diff($implemented, array_column($reference['rules'], 'id'));

        if ($extras !== []) {
            $markdown .= "\n## Implemented beyond the reference\n\n| Rule | Note |\n|---|---|\n";

            foreach ($extras as $extra) {
                $markdown .= '| '.$extra.' | '.self::cell(self::EXTRA_NOTES[$extra] ?? '')." |\n";
            }
        }

        return $markdown;
    }

    /**
     * The full README block, markers included, so the drift test can match exactly.
     */
    public static function readmeBlock(): string
    {
        $reference = self::reference();
        $implemented = self::implementedRuleIds();
        $groups = self::groupedReference($reference['rules']);

        [$done, $partial, $open, $total] = self::totals($groups, $implemented);

        $block = self::README_START."\n\n";
        $block .= "**{$done} rules fully implemented, {$partial} partial, {$open} open** — measured against the official EN 16931 ";
        $block .= 'validation artefacts **'.$reference['sources']['en16931']['version'].'** and the XRechnung Schematron **'.$reference['sources']['xrechnung']['version'].'** ';
        $block .= "({$total} business rules in total). The full per-rule matrix lives in [COVERAGE.md](COVERAGE.md).\n\n";
        $block .= self::renderSummaryTable($groups, $implemented, null);
        $block .= "\n".self::README_END;

        return $block;
    }

    /**
     * @param  array<string, list<array{id: string, set: string, flag: string, text: string}>>  $groups
     */
    private static function renderSummaryTable(array $groups, array $implemented, ?string $heading): string
    {
        $markdown = $heading !== null ? "{$heading}\n\n" : '';
        $markdown .= "| Rule group | ✅ | 🟡 | ❌ | Total |\n|---|--:|--:|--:|--:|\n";

        foreach ($groups as $label => $rules) {
            [$done, $partial, $open] = self::countStatuses($rules, $implemented);
            $markdown .= "| {$label} | {$done} | {$partial} | {$open} | ".count($rules)." |\n";
        }

        [$done, $partial, $open, $total] = self::totals($groups, $implemented);
        $markdown .= "| **Total** | **{$done}** | **{$partial}** | **{$open}** | **{$total}** |\n";

        return $markdown;
    }

    /**
     * @param  array<string, list<array{id: string, set: string, flag: string, text: string}>>  $groups
     * @return array{int, int, int, int}
     */
    private static function totals(array $groups, array $implemented): array
    {
        $done = $partial = $open = $total = 0;

        foreach ($groups as $rules) {
            [$groupDone, $groupPartial, $groupOpen] = self::countStatuses($rules, $implemented);
            $done += $groupDone;
            $partial += $groupPartial;
            $open += $groupOpen;
            $total += count($rules);
        }

        return [$done, $partial, $open, $total];
    }

    /**
     * @param  list<array{id: string, set: string, flag: string, text: string}>  $rules
     * @param  list<string>  $implemented
     * @return array{int, int, int}
     */
    private static function countStatuses(array $rules, array $implemented): array
    {
        $done = $partial = $open = 0;

        foreach ($rules as $rule) {
            [$status] = self::statusFor($rule['id'], $implemented);
            match ($status) {
                '✅' => $done++,
                '🟡' => $partial++,
                default => $open++,
            };
        }

        return [$done, $partial, $open];
    }

    /**
     * @param  list<string>  $implemented
     * @return array{string, string}
     */
    private static function statusFor(string $id, array $implemented): array
    {
        if (isset(self::FORCED_OPEN[$id])) {
            return ['❌', self::FORCED_OPEN[$id]];
        }

        if (isset(self::PARTIAL[$id])) {
            return ['🟡', self::PARTIAL[$id]];
        }

        if (in_array($id, $implemented, true)) {
            return ['✅', self::NOTES[$id] ?? ''];
        }

        return ['❌', ''];
    }

    /**
     * @param  list<array{id: string, set: string, flag: string, text: string}>  $rules
     * @return array<string, list<array{id: string, set: string, flag: string, text: string}>>
     */
    private static function groupedReference(array $rules): array
    {
        $labels = [
            'BR-CO-' => 'BR-CO — conditions & calculations',
            'BR-DEC-' => 'BR-DEC — decimals',
            'BR-CL-' => 'BR-CL — code lists',
            'BR-AE-' => 'BR-AE — Reverse charge',
            'BR-AF-' => 'BR-AF — IGIC (Canary Islands)',
            'BR-AG-' => 'BR-AG — IPSI (Ceuta/Melilla)',
            'BR-IC-' => 'BR-IC — Intra-community supply',
            'BR-S-' => 'BR-S — Standard rated',
            'BR-Z-' => 'BR-Z — Zero rated',
            'BR-E-' => 'BR-E — Exempt from VAT',
            'BR-G-' => 'BR-G — Export outside the EU',
            'BR-O-' => 'BR-O — Not subject to VAT',
            'BR-B-' => 'BR-B — Split payment (Italy)',
        ];

        $order = [
            'BR — core document & line rules',
            ...array_values($labels),
            'BR-DE — XRechnung CIUS',
            'BR-DEX — XRechnung Extension',
        ];

        $groups = array_fill_keys($order, []);

        foreach ($rules as $rule) {
            if ($rule['set'] === 'xrechnung') {
                $groups[str_starts_with($rule['id'], 'BR-DEX') ? 'BR-DEX — XRechnung Extension' : 'BR-DE — XRechnung CIUS'][] = $rule;

                continue;
            }

            $label = 'BR — core document & line rules';

            foreach ($labels as $prefix => $candidate) {
                if (str_starts_with($rule['id'], $prefix)) {
                    $label = $candidate;

                    break;
                }
            }

            $groups[$label][] = $rule;
        }

        return array_filter($groups, static fn (array $groupRules): bool => $groupRules !== []);
    }

    /**
     * @return array{sources: array<string, array{version: string, url: string}>, rules: list<array{id: string, set: string, flag: string, text: string}>}
     */
    private static function reference(): array
    {
        $path = dirname(__DIR__).'/resources/rules-reference.json';
        $json = file_get_contents($path);

        if ($json === false) {
            throw new RuntimeException("Missing {$path} — run: php tools/build-rules-reference.php");
        }

        /** @var array{sources: array<string, array{version: string, url: string}>, rules: list<array{id: string, set: string, flag: string, text: string}>} */
        return json_decode($json, true, 512, JSON_THROW_ON_ERROR);
    }

    /**
     * @return list<string>
     */
    private static function implementedRuleIds(): array
    {
        $ids = [];

        foreach ([...RuleSets::en16931(), ...RuleSets::xrechnung()] as $rule) {
            if ($rule->id() === 'BR-CAT-08') {
                array_push($ids, ...self::CATEGORY_SUM_IDS);

                continue;
            }

            $ids[] = $rule->id();
        }

        $ids = array_values(array_unique($ids));
        sort($ids, SORT_NATURAL);

        return $ids;
    }

    private static function cell(string $text): string
    {
        return str_replace('|', '\\|', $text);
    }
}
